const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  getChains: () => ipcRenderer.invoke("get-chains"),
  getAddresses: (opts) => ipcRenderer.invoke("get-addresses", opts || {}),
  listBooks: () => ipcRenderer.invoke("list-books"),
  getAddressesMulti: (books) => ipcRenderer.invoke("get-addresses-multi", { books }),
  testAddressbook: (path) => ipcRenderer.invoke("test-addressbook", { path }),
  getAddressbookStatus: () => ipcRenderer.invoke("get-addressbook-status"),
  getAbi: (address, chainId) => ipcRenderer.invoke("get-abi", { address, chainId }),
  scanAddress: (address, chainId) => ipcRenderer.invoke("scan-address", { address, chainId }),
  checkCode: (rpcUrl, address) => ipcRenderer.invoke("check-code", { rpcUrl, address }),
  ethGetCode: (rpcUrl, address) => ipcRenderer.invoke("eth-get-code", { rpcUrl, address }),
  ethCall: (rpcUrl, to, data) => ipcRenderer.invoke("eth-call", { rpcUrl, to, data }),
  ethGetBalance: (rpcUrl, address) => ipcRenderer.invoke("eth-get-balance", { rpcUrl, address }),
  rpcBatch: (rpcUrl, requests) => ipcRenderer.invoke("rpc-batch", { rpcUrl, requests }),
  analyzeBytecode: (code) => ipcRenderer.invoke("analyze-bytecode", { code }),
  lookupSignatures: (selectors) => ipcRenderer.invoke("lookup-signatures", { selectors }),
  abiCacheGet: (chainId, address, codehash) => ipcRenderer.invoke("abi-cache-get", { chainId, address, codehash }),
  abiCachePut: (args) => ipcRenderer.invoke("abi-cache-put", args),
  abiCacheBust: (chainId, address) => ipcRenderer.invoke("abi-cache-bust", { chainId, address }),
  safeApiPending: (chainId, safeAddr, currentNonce) => ipcRenderer.invoke("safe-api-pending", { chainId, safeAddr, currentNonce }),
  safeApiHistory: (chainId, safeAddr, opts) => ipcRenderer.invoke("safe-api-history", { chainId, safeAddr, ...(opts || {}) }),
  safeApiByNonce: (chainId, safeAddr, nonce) => ipcRenderer.invoke("safe-api-by-nonce", { chainId, safeAddr, nonce }),
  safeApiInfo: (chainId, safeAddr) => ipcRenderer.invoke("safe-api-info", { chainId, safeAddr }),
  safeApiPropose: (args) => ipcRenderer.invoke("safe-api-propose", args),
  safeApiConfirm: (args) => ipcRenderer.invoke("safe-api-confirm", args),
  safeApiExec: (args) => ipcRenderer.invoke("safe-api-exec", args),
  safeScanStart: (args) => ipcRenderer.invoke("safe-scan-start", args),
  safeScanCancel: (scanId) => ipcRenderer.invoke("safe-scan-cancel", { scanId }),
  rpcGetLogs: (args) => ipcRenderer.invoke("rpc-get-logs", args),
  rpcEndpointsGet: (args) => ipcRenderer.invoke("rpc-endpoints-get", args),
  rpcEndpointsRefresh: () => ipcRenderer.invoke("rpc-endpoints-refresh"),
  rpcStateReset: () => ipcRenderer.invoke("rpc-state-reset"),
  discoveredSafesList: () => ipcRenderer.invoke("discovered-safes-list"),
  discoveredSafesRemove: (chainId, safeAddr) => ipcRenderer.invoke("discovered-safes-remove", { chainId, safeAddr }),
  discoveredSafesClear: () => ipcRenderer.invoke("discovered-safes-clear"),
  onSafeScanProgress: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("safe-scan-progress", h); return () => ipcRenderer.removeListener("safe-scan-progress", h); },
  onSafeScanHit: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("safe-scan-hit", h); return () => ipcRenderer.removeListener("safe-scan-hit", h); },
  onSafeScanDone: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("safe-scan-done", h); return () => ipcRenderer.removeListener("safe-scan-done", h); },
  tenderlySimulate: (args) => ipcRenderer.invoke("tenderly-simulate", args),
  tenderlyShare: (args) => ipcRenderer.invoke("tenderly-share", args),
  openExternal: (url) => ipcRenderer.invoke("open-external", { url }),
  safeBuildTypedData: (args) => ipcRenderer.invoke("safe-build-typed-data", args),
  safeExecTransaction: (args) => ipcRenderer.invoke("safe-exec-transaction", args),
  ethGetReceipt: (rpcUrl, txHash) => ipcRenderer.invoke("eth-get-receipt", { rpcUrl, txHash }),
  trezorInit: () => ipcRenderer.invoke("trezor-init"),
  trezorListAccounts: (opts) => ipcRenderer.invoke("trezor-list-accounts", opts || {}),
  trezorSignTyped: (args) => ipcRenderer.invoke("trezor-sign-typed", args),
  trezorVerifyAddress: (args) => ipcRenderer.invoke("trezor-verify-address", args),
  trezorCancel: (reason) => ipcRenderer.invoke("trezor-cancel", { reason }),
  trezorDispose: () => ipcRenderer.invoke("trezor-dispose"),
  loadSettings: () => ipcRenderer.invoke("load-settings"),
  saveSettings: (data) => ipcRenderer.invoke("save-settings", data),
  listBatches: () => ipcRenderer.invoke("list-batches"),
  saveBatch: (batch) => ipcRenderer.invoke("save-batch", batch),
  deleteBatch: (id) => ipcRenderer.invoke("delete-batch", id),
  onSafeRateLimit: (cb) => {
    const handler = (_event, data) => cb(data);
    ipcRenderer.on("safe-rate-limit", handler);
    return () => ipcRenderer.removeListener("safe-rate-limit", handler);
  },
  onShowAbout: (cb) => {
    const handler = (_event, data) => cb(data);
    ipcRenderer.on("show-about", handler);
    return () => ipcRenderer.removeListener("show-about", handler);
  },
});
